OK-509: Valintakoekutsut-näkymä
Opetushallitus/valintojen-toteuttaminen pull request #35
Opened 2024-08-21 13:56 UTC by pretseli

Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Kyllä/En
Oletko tarkistanut ja päivittänyt riippuvuudet? Kyllä/En
Oletko kokeillut toimiiko käyttöliittymä mobiilissa landscape moodissa? Kyllä/En/Ei koske
Oletko testannut että lisäämäsi toiminto on saavutettava? Kyllä/En/Ei koske

2024-09-13 14:06 UTC, SalamaGofore requested changes
Hyviä muutoksia. Jonkun verran löysin refaktoroitavaa uudelleen jäsenneltävää. En katsonut yhtä kunnolla vielä loppuun, pitää miettiin miten toi valintakoe koodi asettuu tuon 510 kans mikä kans käyttää valintakokeita.

2024-09-13 14:06 UTC, SalamaGofore commented on src/app/lib/valintalaskentakoostepalvelu.ts
> +import { getValintakokeet, ValintakoeData } from './valintaperusteet';
Täytyy katselmoinda vielä tämä filu tarkemmin. Mulla on siinä toisessa pullarissa jonkin verran myös valintakokeisiin liittyvää kamaa. Ja valintakokeet myös

2024-09-16 05:45 UTC, SalamaGofore commented on src/app/haku/[oid]/hakukohde/[hakukohde]/valintakoekutsut/valintakoekutsut-table.tsx
> +const hakijaColumn = makeExternalLinkColumn<ValintakoeKutsuItem>({
Tein tästä omaan pullariini, voin laittaa kuosiin mergen yhteydessä

2024-09-17 11:42 UTC, pretseli commented on src/app/haku/[oid]/hakukohde/[hakukohde]/valinnan-hallinta/hallinta-table.tsx
> -          rowGap: theme.spacing(2),
Jos tehdään styled-funktiolla, silloin `theme` tulee sinne parametrina ja on pakko käyttää `theme.spacing`. `sx`-propilla ei tarvi, vaan voi suoraan laittaa numeron. Viimeisimpien `oph-design-system`-muutosten jälkeen teemaa ei enää voi importoida, mikä oli muutenkin väärä tapa käyttää teemaa komponenteissa.

2024-09-18 06:20 UTC, pretseli commented on src/app/components/table/list-table.tsx
> +            {checkboxSelection && (
Tämä on apinoitu MUI:n DataGridistä: https://mui.com/x/api/data-grid/data-grid/#data-grid-prop-checkboxSelection . En ehkä tässä vaiheessa lähtisi kovin suuresti refaktoroimaan. Voin siirtää tuohon ominaisuuteen liittyviä juttuja omaan tiedostoonsa.

2024-09-18 06:21 UTC, pretseli commented on src/app/lib/valintalaskentakoostepalvelu.ts
> +  const missingHakemusOids = difference(
Mistäköhän tuon vois tarkistaa? Vanhassa toteutuksessa oli tehty noin. Toki mielelläni poistan, jos ei tarvita.

2024-09-18 06:40 UTC, pretseli commented on src/app/haku/[oid]/hakukohde/[hakukohde]/valintakoekutsut/useValintakoekutsutPaginated.ts
> +'use client';
Varmaan tämän pitäsi mennä samalla tavalla kuin komponenteissakin. Koska on hyvä idea sijoittaa koodi mahdollisimman lähelle sitä paikkaa missä sitä käytetään, niin ehkä meidän pitäis laittaa nämäkin route-hakemistoon silloin kun käytetään vain yhdessä paikassa. Olisko siis hyvä, että jokaisessa route-hakemistossa olis myös mahdollisesti hakemistot `hooks`, `components` ja `lib`? Jos halutaan, että ne erottuu Next.js:n jutuista niin sitten jokin etuliite?

2024-09-18 09:20 UTC, pretseli commented on src/app/haku/[oid]/hakukohde/[hakukohde]/valintakoekutsut/page.tsx
> +        <Box display="flex" flexDirection="column" alignItems="center" gap={2}>
Toteutettu NoResults-komponentti ja otettu käyttöön

2024-09-18 09:22 UTC, pretseli commented on src/app/components/table/list-table.tsx
> +            {checkboxSelection && (
Siirsin nuo omaan tiedostoonsa ja refaktoroin tuota tiedostoa vähän muutenkin pienemmiksi paloiksi.

2024-09-18 09:33 UTC, SalamaGofore approved these changes

2024-09-18 09:36 UTC, merged