OK-674: Henkilöittäin-näkymän valintalaskenta
Opetushallitus/valintojen-toteuttaminen pull request #58
Opened 2024-12-20 07:33 UTC by pretseli

Oletko lisännyt tarvittavat yksikkö- tai ui-testit toiminnallisuudelle? Kyllä
Oletko tarkistanut ja päivittänyt riippuvuudet? En
Oletko kokeillut toimiiko käyttöliittymä mobiilissa landscape moodissa? Kyllä
Oletko testannut että lisäämäsi toiminto on saavutettava? En

2024-12-23 15:34 UTC, SalamaGofore requested changes

2024-12-23 15:34 UTC, SalamaGofore commented on src/app/lib/state/laskenta-state.test.ts
> +  console.log({ yhteenveto });
pois

2024-12-23 15:34 UTC, SalamaGofore commented on src/app/lib/state/laskenta-state.ts
> +              // TODO: Poista errorSummary, kun virheiden esittäminen on yhdenmukaistettu myös sijoittelun tulokset näkymässä
valinnan hallinta näkymässä?

2025-01-07 06:32 UTC, pretseli commented on src/app/components/error-alert.tsx
> +    : null;
Tämä on nyt käytössä valinnan hallinnassa myös, ja kyllä tälläkin yhden virheen näyttäminen onnistuu. On vain vähän lyhyemmin toteutettu.

2025-01-07 06:41 UTC, pretseli commented on src/app/haku/[oid]/henkilo/[hakemusOid]/components/confirmation-modal-dialog.tsx
> +import { OphModalDialog } from '@/app/components/oph-modal-dialog';
Kyllä ajatus oli, että tätä voisi käyttää muuallakin, mutta en nyt lähtenyt vielä muuttamaan muualle. Myös konfirmaatio-notifikaation voi korvata tällä. Lisäilen pari TODO-kommenttia tästä.

2025-01-07 07:21 UTC, SalamaGofore approved these changes

2025-01-07 07:22 UTC, merged